import dedent from 'string-dedent'
import { fromFileUrl, relative } from '@std/path'

export async function build() {
	console.info('Rebuilding user script...')

	const [metadata, script, styles] = await Promise.all([
		'./src/metadata.txt',
		'./src/script.mjs',
		'./src/styles.css',
	].map((path) => Deno.readTextFile(path)))

	const userScript = dedent`
		${metadata.trim()}

		// 🚨 Generated by ~/${relative('.', fromFileUrl(import.meta.url))}, do not edit directly.

		${script.trim()}
		
		const style = document.createElement('style')
		void (document.head ?? document.documentElement).append(style)
		style.textContent = ${JSON.stringify(styles.trim())}
	`

	await Deno.writeTextFile('./dist/omniglot-hover.user.js', userScript)
	await new Deno.Command('deno', {
		args: ['fmt', './dist/omniglot-hover.user.js'],
	}).spawn().output()
}
